Revert "cpufreq: schedutil: Avoid unnecessary kthread wakeup"
This is prolly an EAS commit, dependent on walt. It needs -fPIC to
compile,
kernel/built-in.o: In function `sugov_init':
/home/runner/msm-4.4/out/../kernel/sched/cpufreq_schedutil.c:715:
undefined reference to `walt_ravg_window'
/home/runner/msm-4.4/aarch64-linux-android-4.9/bin/aarch64-linux-android-ld:
kernel/built-in.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against
external symbol `walt_ravg_window' can not be used when making a shared
object; recompile with -fPIC
/home/runner/msm-4.4/out/../kernel/sched/cpufreq_schedutil.c:715:
undefined reference to `walt_ravg_window'
make[1]: *** [vmlinux] Error 1
make[1]: Leaving directory `/home/runner/msm-4.4/out'
make: *** [sub-make] Error 2

This reverts commit 65469105e6d4bd6531cb1f9e7b0f3b207195df28.